keys:
  # Age public key from target machine (sensors)
  - &sensors_key age1hk560j8ymc8t0jcdnwxl8rft5mrsfzjyxedvenuhwnnqzfu84qjspq7rv2

creation_rules:
  - path_regex: .*\.(yaml|env)$
    key_groups:
      - age:
          - *sensors_key
