keys:
  # Age public key from target machine (sensors) - derived from SSH host key
  - &sensors_key age10dm8xrylhqj3jfmp9e6jnfnfd9k6kntluhff0qxseu36nnjj0udqp032vy
  # Age public key from dev machine (junior) - derived from SSH host key
  - &junior_key age1ywrnya3a0jduxy7lrfv0vd0g37e8996hnm6afzv3q3n20tplrgcs50tum8

creation_rules:
  - path_regex: .*\.(yaml|env)$
    key_groups:
      - age:
          - *sensors_key
          - *junior_key
